config/routes.rb
RockPaperScissors::Application.routes.draw do

  root 'rockpaperscissors#index'

    resources :rockpaperscissors

end

app/models/rockpaperscissor.rb
class Rockpaperscissor < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/rockpaperscissors_controller.rb
class RockpaperscissorsController < ApplicationController

	def index
		@options = Rockpaperscissor.all
	end

	def show
		id = params[:id]
		@choice = Rockpaperscissor.find(id)

		game = ["Rock", "Paper", "Scissors"]
		@opponents_choice = game.sample

		game_logic(@choice, @opponents_choice)


	end


	def game_logic(player, computer)
		if player.win == computer
			@end_message = "Win! You defeated"
			@image = "http://media.tumblr.com/tumblr_ls72l5yoJb1qjbeju.gif"
		elsif player.lose == computer
			@end_message = "Lose! You were defeated by"
			@image = "http://cdn.rsvlts.com/wp-content/uploads/2013/03/some_seriously_bad_timing_fails_17.gif"
		elsif player.tie == computer
			@end_message = "Tie!"
			@image = "http://i2.kym-cdn.com/photos/images/newsfeed/000/447/579/465.gif"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rockpaperscissors_helper.rb
module RockpaperscissorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RockPaperScissors</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rockpaperscissors/index.html.erb
<h1>Welcome to Rock, Paper, Scissors 2.0</h1>

<p>Please pick your weapon of choice</p>

<% @options.each do |option| %>
	<p><%= option.name %>
	<%= link_to "Select", rockpaperscissor_path(option.id) %></p>
<% end %>

app/views/rockpaperscissors/show.html.erb
<h1>Results Page</h1>

<p>Your choice: <%= @choice.name %></p>
<p>Opponent's choice: <%= @opponents_choice %></p>

<img src="<%=@image%>">

<h2><%= @end_message %> <%= @opponents_choice %></h2>

<br>
<%= link_to "Play Again", rockpaperscissors_path %>

<%= image_tag("http://www.roflzoo.com/pics/201111/smiling-dog-big.jpg") %>